### ISSUE TITLE
contain minZoom not show correct values

### ISSUE THREAD

**Issue by Keun** [armin-pfaeffle/ap-image-zoom#2]
Hi,

First lets kick off with the comment: I love you library :+1: 

I noticed that when i set minZoom : 'contain' the image is not showing correctly. The values of the matrix3d transform are not correctly calculated?

I have an 5000x3000 image that i want to use. When I reload an image using 'destroy' and init it again, it works fine, only the first init is not working.

**Comment by armin-pfaeffle** [comment]
Hey! Thanks ;) I will have a look at it!

**Edit**: Can you post your code here? What browser do you use? Perhaps it's a browser thing.

**Comment by Keun** [comment]
I fixed the problem. Good news: It was not the library ;) 

I used an animation to show an popup. I forgot the to init the library AFTER (callback) the animation is done.... -.-

My bad, sorry.

**Comment by armin-pfaeffle** [comment]
Nice to hear that everything works as expected ;)

But you remembered me to write the documentation for that plugin...
